add DatalandEDC and PostgreSQL to architecture diagram
d-fine/Dataland pull request #19
Opened 2022-03-31 13:00 UTC by ppuetsch

# Pull Request Architecture Diagram including DatalandEDC
## Things to do during Peer Review
Please check all boxes before the Pull Request is merged. In case you skip a box, describe in the PRs description (that means: here) why the check is skipped.
- [ ] The code has been manually inspected
- [ ] The new feature was observed "in running software"
- [ ] The DoD was checked for completeness
- [ ] The PR actually implements what is described in the JIRA-Issue
- [ ] At least one E2E Test exists testing the new feature
- [ ] Documentation is updated as required
- [ ] The new version is deployed to preview using this branch
  - [ ] It's verified that this version actually is the one deployed (check actuator/info for branch name and commit id!)
  - [ ] The new feature is manually used/tested/observed on preview

2022-03-31 13:49 UTC, StephanSinn requested changes

2022-03-31 13:49 UTC, StephanSinn commented on documentation/architecture.drawio
> +<mxfile host="app.diagrams.net" modified="2022-03-31T09:36:37.073Z" agent="5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36" etag="lK_5tippkE
Blaue Box. Ist ein "Reverse Proxy" nicht schon der Begriff für Inbound Kommunikation? 
Also: "Dataland Inbound Reverse Proxy" should be "Dataland Reverse Proxy" OR "Dataland Inbound Proxy"

2022-03-31 13:49 UTC, StephanSinn commented on documentation/architecture.drawio
>    <diagram id="EgJ7EEfOsz50NrqOtSAN" name="Page-1">
Der Skyminder Client hat eine extra Box (hellblau innerhalb Dataland Backend), EDC Clients nicht. Das sollte konsistent sein.

2022-03-31 13:49 UTC, StephanSinn commented on documentation/architecture.drawio
> +    <mxGraphModel dx="1955" dy="1185" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1169" pageHeight="827" math="0" shadow="0">
Mir fällt es schwer aus dem Architecture Diagram hilfreiche architektur schemata abzuleiten, zB. was ist ein MicroService

2022-03-31 14:33 UTC, ppuetsch commented on documentation/architecture.drawio
> +    <mxGraphModel dx="1955" dy="1185" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1169" pageHeight="827" math="0" shadow="0">
wie besprochen: PostgreSQL bleibt gemäß Abstimmung Teil des Backend, ansonsten noch Legendeneintrag für "Datalandinternal Microservice" hinzugefügt.

2022-03-31 14:34 UTC, ppuetsch commented on documentation/architecture.drawio
>    <diagram id="EgJ7EEfOsz50NrqOtSAN" name="Page-1">
Habe EDC Client hinzugefügt

2022-04-01 09:00 UTC, StephanSinn commented on documentation/architecture.drawio
> +<mxfile host="app.diagrams.net" modified="2022-03-31T09:36:37.073Z" agent="5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.84 Safari/537.36" etag="lK_5tippkE
Oki doki, danke für den Link.

2022-04-01 09:00 UTC, StephanSinn commented on documentation/architecture.drawio
>    <diagram id="EgJ7EEfOsz50NrqOtSAN" name="Page-1">
lgtm

2022-04-01 09:00 UTC, StephanSinn commented on documentation/architecture.drawio
> +    <mxGraphModel dx="1955" dy="1185" grid="1" gridSize="10" guides="1" tooltips="1" connect="1" arrows="1" fold="1" page="1" pageScale="1" pageWidth="1169" pageHeight="827" math="0" shadow="0">
lgtm

2022-04-01 14:48 UTC, merged