Dala 1 init coverage
d-fine/Dataland pull request #3
Opened 2022-02-15 14:11 UTC by StephanSinn

2022-02-15 20:29 UTC, SiegfriedSobkowiak requested changes

2022-02-15 20:29 UTC, SiegfriedSobkowiak commented on src/test/kotlin/org/dataland/datalandbackend/controller/DataControllerTest.kt
> +    val dataSets = listOf(
Wieso wurde der Typ der Listenobjekte entfernt?

2022-02-15 20:29 UTC, SiegfriedSobkowiak commented on src/test/kotlin/org/dataland/datalandbackend/controller/DataControllerTest.kt
> +    /* val dataStore = DataStoreInterface()
Auskommentierter Code sollte entfernt werden.

2022-02-15 20:29 UTC, SiegfriedSobkowiak commented on src/main/kotlin/org/dataland/datalandbackend/interfaces/DataStoreInterface.kt
> -    fun addDataSet(dataSet: DataSet): DataSetMetaInformation
Hier ist scheinbar etwas beim merge schief gelaufen und eine alte Version des Codes ist wieder da.

2022-02-15 20:29 UTC, SiegfriedSobkowiak commented on src/test/kotlin/org/dataland/datalandbackend/interfaces/DataStoreInterfaceTest.kt
> +internal class DataStoreInterfaceTest : DataStoreInterface {
Nach der Entfernung der Default Implementierungen ist dieser  Test nicht mehr nötig (das gesamte File).

2022-02-15 20:29 UTC, SiegfriedSobkowiak commented on src/test/kotlin/org/dataland/datalandbackend/service/InMemoryDataStoreTest.kt
> +    fun `Check id after adding multiple new data`() {
Dieser Test ist die Alte Version des letzten Tests und kann raus.

2022-02-15 20:29 UTC, SiegfriedSobkowiak commented on src/test/kotlin/org/dataland/datalandbackend/service/InMemoryDataStoreTest.kt
> +        println(testStore.listDataSets())
Warum ist hier ein print?

2022-02-15 20:29 UTC, SiegfriedSobkowiak commented on src/test/kotlin/org/dataland/datalandbackend/service/InMemoryDataStoreTest.kt
> +    fun `Add and retrieve data as a list and check dataset 0`() {
Aus meiner Sicht ist die folgende Gruppe von 3 Tests redundant. Man testet ja im Grunde immer das gleiche.

2022-02-16 07:56 UTC, StephanSinn commented on src/test/kotlin/org/dataland/datalandbackend/controller/DataControllerTest.kt
> +    val dataSets = listOf(
Hat intellij vorgeschlagen, vllt weil Kotlin ja dieses Type Inference macht.

2022-02-16 07:59 UTC, StephanSinn commented on src/test/kotlin/org/dataland/datalandbackend/service/InMemoryDataStoreTest.kt
> +        println(testStore.listDataSets())
wurde entfernt

2022-02-16 08:00 UTC, StephanSinn commented on src/test/kotlin/org/dataland/datalandbackend/service/InMemoryDataStoreTest.kt
> +    fun `Check id after adding multiple new data`() {
wurde entfernt

2022-02-16 08:12 UTC, StephanSinn commented on src/main/kotlin/org/dataland/datalandbackend/interfaces/DataStoreInterface.kt
> -    fun addDataSet(dataSet: DataSet): DataSetMetaInformation
habe ich korrigiert

2022-02-16 08:12 UTC, StephanSinn commented on src/test/kotlin/org/dataland/datalandbackend/interfaces/DataStoreInterfaceTest.kt
> +internal class DataStoreInterfaceTest : DataStoreInterface {
file wurde gelöscht

2022-02-16 15:11 UTC, SiegfriedSobkowiak commented on src/test/kotlin/org/dataland/datalandbackend/controller/DataControllerTest.kt
> +    val dataSets = listOf(
Das Stimmt, dann kann es auch raus.

2022-02-16 15:13 UTC, SiegfriedSobkowiak commented on src/test/kotlin/org/dataland/datalandbackend/service/InMemoryDataStoreTest.kt
> +        assertEquals(dataSets[1], testStore.getDataSet("0")) // why having starting id == 0 not 1?
Der Kommentar sollte noch raus. Wir können das gerne ändern das die IDs bei 1 beginnen.

2022-02-16 15:24 UTC, StephanSinn commented on src/test/kotlin/org/dataland/datalandbackend/service/InMemoryDataStoreTest.kt
> +        assertEquals(dataSets[1], testStore.getDataSet("0")) // why having starting id == 0 not 1?
erledigt

2022-02-16 15:39 UTC, SiegfriedSobkowiak approved these changes

2022-02-16 15:41 UTC, merged