Pre-visit Test and more
d-fine/Dataland pull request #41
Opened 2022-05-13 08:03 UTC by ppuetsch

# Pull Request Pre-visit Test and more
This PR adds a Test that visits each Company/Taxnonomy Information to have everything cached once the deployment is done.
This PR contains minor improvements
## Things to do during Peer Review
Please check all boxes before the Pull Request is merged. In case you skip a box, describe in the PRs description (that means: here) why the check is skipped.
- [x] The Github Actions (including Sonarqube Gateway and Lint Checks) are green. This is enforced by Github. 
- [ ] A peer-review has been executed
  - [ ] The code has been manually inspected by someone who did not implement the feature
  - [ ] The new feature was observed "in running software"
- [ ] The PR actually implements what is described in the JIRA-Issue
- [ ] At least one E2E Test exists testing the new feature
- [ ] Documentation is updated as required
- [ ] The automated deployment is updated if required
- [ ] The new version is deployed to preview using this branch
  - [ ] It's verified that this version actually is the one deployed (check actuator/info for branch name and commit id!)
  - [ ] The new feature is manually used/tested/observed on preview
- [ ] There is at least one picture for each story, which was created before coding has started

2022-05-13 08:13 UTC, SiegfriedSobkowiak approved these changes

2022-05-18 09:47 UTC, ppuetsch commented on dataland-frontend/tests/e2e/specs/high/Prepopulation.ts
> +        let promise = Promise.resolve()
geändert.

2022-05-18 15:10 UTC, ppuetsch commented on dataland-frontend/tests/e2e/specs/high/Prepopulation.ts
> +        let promise = Promise.resolve()
Jetzt ist es wieder let - weil es jetzt auch reassigned wird.

2022-05-19 06:44 UTC, StephanSinn requested changes

2022-05-19 06:44 UTC, StephanSinn commented on .github/workflows/CD.yaml
> +          ELECTRON_EXTRA_LAUNCH_ARGS: "--ignore-connections-limit=localhost:8090,proxy,localhost,preview-dataland.duckdns.org,dev-dataland.duckdns.org"
können wir feststellen, dass diese Änderungen wirklich einen effekt hatten in der CI?

2022-05-19 06:44 UTC, StephanSinn commented on dataland-frontend/tests/e2e/support/utility.ts
> +export function doThingsInChunks<T>(dataArray: Array<T>, chunkSize: number, processor: (element: T)=>void): Promise<any> {
Diese Funktion scheint nun die Lösung der Probleme zu sein. Können wir darüber reden?

2022-05-19 06:44 UTC, StephanSinn commented on dataland-frontend/tests/e2e/specs/high/Prepopulation.ts
> +        function uploadSingleElementOnce(endpoint: string, element: object): Promise<void> {
diskutierbare Frage: für die Übersichtlichkeit wäre es vllt ganz gut functionen in die datei utility.ts auszulagern und in den test files nur tests zu lassen?

2022-05-19 06:44 UTC, StephanSinn commented on dataland-inbound-proxy/nginx.conf
> +    location /edc/api/dataland/eurodat {
wann und wieso hat sich dieser endpunkt geändert?

2022-05-19 07:46 UTC, StephanSinn approved these changes

2022-05-19 19:02 UTC, ppuetsch commented on docker-compose.yml
> +    image: ghcr.io/d-fine/datalandedc/edcdummyserver:0.2.0-SNAPSHOT
Noch finales Release 0.2.0 verwenden, sobald DatalandEDC gemerged wurde & Release veröffentlicht wurde.

2022-05-20 09:06 UTC, SiegfriedSobkowiak commented on docker-compose.yml
> +    image: ghcr.io/d-fine/datalandedc/edcdummyserver:0.2.0-SNAPSHOT
version ist aktualisiert

2022-05-20 11:52 UTC, StephanSinn approved these changes

2022-05-20 14:19 UTC, emanueldfine commented on README.md
> +* Note: fastXML is managed by spring and ktlint by jlleitschuh, thus NO manuel version update should be conducted
"manual" statt "manuel"

2022-05-20 14:20 UTC, emanueldfine commented on README.md
> +* Note: fastXML is managed by spring and ktlint by jlleitschuh, thus NO manuel version update should be conducted
und heißt es nicht "fasterXML" ?  bin mir grad nicht sicher

2022-05-20 14:24 UTC, emanueldfine commented on dataland-backend/src/main/resources/application-development.properties
> +dataland-edc-client.base-url=http://localhost:9191/api
Wieso musste das umgestellt werden?

2022-05-20 14:26 UTC, emanueldfine commented on dataland-frontend/tests/e2e/specs/dev/DataIntegrity.ts
> +        cy.retrieveDataIdsList().then((dataIdList: Array<string>) => {
Habe den Test beim Lesen des Titels nicht genau verstanden. Könnte man das sprechender formulieren?

2022-05-20 17:25 UTC, SiegfriedSobkowiak commented on dataland-frontend/tests/e2e/specs/dev/DataIntegrity.ts
> +        cy.retrieveDataIdsList().then((dataIdList: Array<string>) => {
wurde von Stephan angepasst

2022-05-20 17:26 UTC, SiegfriedSobkowiak commented on README.md
> +* Note: fastXML is managed by spring and ktlint by jlleitschuh, thus NO manuel version update should be conducted
wurde angepasst

2022-05-20 17:27 UTC, merged